### ISSUE TITLE
Remove git integration

### ISSUE THREAD

**Issue by jfairley** [conveyal/maven-semantic-release#17]
I'm torn over the fact that this plugin performs git commits and pushes. While it's not actually a problem, since I also use git, it's technically overreaching.

The more correct thing to do would be simply execute the necessary maven commands to deploy a new artifact and leave the SCM-related stuff to the other semantic-release plugins that are built for it.

In this case the relevant plugin is [`@semantic-release/git`](https://github.com/semantic-release/git). This plugin _does_ have an NPM default configuration, but I have used it successfully with the following configuration:

```javascript
plugins: [
 '@semantic-release/git', { assets: [ 'pom.xml' ] }
]
```

**Comment by evansiroky** [comment]
Right, I noticed that when building this.  In order to use Conveyal's release workflow, we needed to have more commands than were available in @semantic-release/git for performing various git operations that enables us to make commits, checkout other branches and perform merges.  Our own workflow is beyond the minimum required, but all of that is optional and disabled by default.  I had a good discussion about this when adding this library to the list of community plugins for semantic-release over here: https://github.com/semantic-release/semantic-release/pull/997.  The semantic-release maintainer seemed to be happy with making these custom workflows optional and disabled by default.
